### PR TITLE
CU-23dqzz6 Feature minelucks.ts unit tests

### PR DESCRIPTION
**Pull request by rkamysz**
The purpose of this PR is to add unit tests to the `mineluck.ts` file. 
First, I had to break down the code so that any tests could be created.  Remember that the code structure is temporary, this PR was not intended for refactoring.

Tests and necessary data were created in the directory `__tests__` in the location of the tested file.
These are our first unit tests, form may change. In this case, these tests also need to be adjusted

### CODE REVIEW

**Comment by dskvr** [comment]
Task linked: [CU-23dqzz6 Write unit tests for minelucks.ts api handler](https://app.clickup.com/t/23dqzz6)

**Comment by ktamas77** [comment]
@rkamysz looks good, please resolve conflicts & good to go.

**Comment by rkamysz** [comment]
Ive added few more tests, new settings for coverage 
`mineluck.ts` stats
```
-----------------------|---------|----------|---------|---------|-------------------
File                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-----------------------|---------|----------|---------|---------|-------------------
mineluck.ts            |   91.11 |      100 |      75 |   90.69 | 197-207
```

**Review by ktamas77 — APPROVED** [review]
very cool! glad to see increasing coverage.

**Pull request merged**
