### PR TITLE
Dockerized version

### PR DESCRIPTION
**Pull request by ktamas77**
Please see updated `README.md` for detailed instructions.

### CODE REVIEW

**Comment by dallasjohnson** [comment]
I've tried it and as it is doesn't work for me. For the API to be running correctly it needs to connect to RabbitMQ which was not present in the docker-compose file. Also It needs to have the `processor.js`, `filler.js`, `blockrange.js` and the `api.js` running in parallel with RabbitMQ facilitating all the async processing between the 3 processes to ingest into Mongo plus the API to provide access. I've added some configs and added RabbitMQ to docker-compose but still don't have the other processes starting in parallel. I'm not sure of the best way to achieve that in docker-compose and to ensure they all wait for Rabbit MQ to be ready before trying to run

**Comment by ktamas77** [comment]
@dallasjohnson thank you for your feedback!
The following changes/improvements has been added:
- RabbitMQ added to a separate container
- Docker compose upgraded to v3 syntax - this way rabbitMQ can self-health check until it comes online
- The RabbitMQ dependent services will keep connecting / restarting until they have a successful connection. All services are running in their own isolated containers.
- RabbitMQ is mapped to the host OS, admin is accessible at http://localhost:15672 with the default login (guest/guest)

To rebuild + run, just use
`docker compose up --build`

Once it's built, second run will be much faster:
`docker compose up`

The Mongo Database stored on a persistent volume, everything else will reset to the build state on each restart.
Please let me know if you have any further questions / requests.

**Comment by ktamas77** [comment]
Example screenshots:

Screen Shot 2021-11-08 at 8 28 58 AM
>

**Comment by dallasjohnson** [comment]
Looks good to me. I have some other changes to add with flag options for the filler process but I'll add them as a separate commit once merged.

**Pull request merged**
