### PR TITLE
Asset api tests

### PR DESCRIPTION
**Pull request by montera82**
image

### CODE REVIEW

**Review by rkamysz — APPROVED** [review]

**Comment by ktamas77** [comment]
@montera82 how are we running tests? could you please update the `test` command in `package.json` accordingly?
cc @rkamysz

**Comment by rkamysz** [comment]
@ktamas77 why he should update the `test` command? `test` command is now split into `test:api` and `test:unit` commands. Both commands runs `jest` with given config. Do we really need another command to run docker?

PS this `test-docker` is not a good name.

**Comment by montera82** [comment]
i agree @rkamysz what name should we call it?

**Comment by ktamas77** [comment]
> PS this `test-docker` is not a good name.

I agree 100%.

there should be only `test:unit` and `test:api`.

the word *docker* should never be used in `package.json` since jest has no concept whether it's running inside or outside of a container, it's entirely independent from that.

Examples:

Good:

✅ `docker compose run api yarn test:unit`
✅ `docker compose run api yarn test:api`

Bad:
❌ `docker compose run api yarn docker-test`

**Review by ktamas77 — CHANGES_REQUESTED** [review]
Please rename `test-docker` accordingly in the `package.json` file

**Comment by montera82** [comment]
closed based on rads work on #33

**Pull request closed without merging**
